const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const base = process.env.VCM_PORTAL_URL || 'http://127.0.0.1:8080';
(async () => {
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const asset={id:'asset-a',tenant_id:'a',environment_id:'env-a',environment_name:'Production',environment_kind:'production',ip:'192.0.2.42',fqdn:'srv <img src=x>.example.test',hostname_netbios:'SRV42',os:'Windows Server 2022',criticality:3,tags:{tier:'critical'},first_seen:'2026-09-01T12:00:00Z',last_seen:'2026-09-30T12:00:00Z',open_findings:2,open_critical_high:1};
  let fail=false;
  await page.route('**/api/**',route=>{
   const url=new URL(route.request().url()), path=url.pathname;
   let body;
   if(path==='/api/tenants') body=[{id:'a',name:'Client A'},{id:'b',name:'Client B'}];
   else if(path.includes('/tenants/')) body=[{id:'env-'+path.split('/')[3],name:'Production'}];
   else if(path==='/api/assets') {
    if(fail)return route.fulfill({status:503,body:'unavailable'});
    const offset=Number(url.searchParams.get('offset')),limit=Number(url.searchParams.get('limit'));
    body={items:url.searchParams.get('os_family')==='unknown'?[]:Array.from({length:Math.max(0,Math.min(limit,51-offset))},(_,i)=>({...asset,id:'asset-'+(offset+i),ip:'192.0.2.'+(offset+i+1)})),total:url.searchParams.get('os_family')==='unknown'?0:51,offset,limit};
   }else if(path.endsWith('/findings'))body={items:[{id:1,rule_id:'10042',rule_title:'Rule <img src=x>',kind:'vulnerability',severity:'high',status:'risk_accepted',scanner:'tenable_nessus',port:443,protocol:'tcp',environment_name:'Previous environment',first_seen:asset.first_seen,last_seen:asset.last_seen}],total:1,offset:0,limit:25};
   else if(path.endsWith('/moves'))body={items:[{id:1,from_environment_name:'Previous environment',to_environment_name:'Production',reason:'Retain <b>history</b>',moved_at:asset.last_seen}],total:1,offset:0,limit:25};
   else if(path.endsWith('/imports'))body={items:[{id:'import-a',filename:'fixture <img src=x>.nessus',scanner:'tenable_nessus',environment_name:'Previous environment',status:'completed',created_at:asset.last_seen}],total:1,offset:0,limit:25};
   else body=asset;
   return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
  });
  await page.goto(base+'/assets.html');
  await page.getByText('Select a client to load assets.',{exact:true}).waitFor();
  await page.locator('#tenant').selectOption('a');
  await page.getByText('51 assets matching this scope and filters.').waitFor();
  assert.equal(await page.locator('img').count(),0);
  await page.locator('#os-search').fill('Not applied yet');
  await page.locator('#next').click();
  await page.getByText('51–51 of 51',{exact:true}).waitFor();
  assert.equal(new URL(page.url()).searchParams.get('offset'),'50');
  assert.equal(new URL(page.url()).searchParams.get('os_search'),null);
  await page.locator('#asset-rows a').click();
  await page.locator('#asset-detail').waitFor();
  await page.getByText('Retain <b>history</b>',{exact:true}).waitFor();
  assert.equal(await page.locator('img').count(),0);
  assert((await page.locator('#asset-fields').textContent()).includes('Windows Server 2022'));
  assert((await page.locator('#findings-rows').textContent()).includes('Previous environment'));
  assert((await page.locator('#findings-rows').textContent()).includes('risk accepted'));
  await page.screenshot({path:'/tmp/vcm-asset-detail.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'/tmp/vcm-asset-detail-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#back-to-assets').click();
  await page.getByText('51–51 of 51',{exact:true}).waitFor();
  assert.equal(new URL(page.url()).searchParams.get('offset'),'50');
  assert(await page.locator('#asset-rows a').evaluate(el=>el===document.activeElement));
  await page.locator('#os-family').selectOption('windows');
  await page.locator('#os-search').fill('Server 2022');
  await page.locator('#tags').fill('tier:critical\nlocation');
  await page.getByRole('button',{name:'Apply filters',exact:true}).click();
  await page.getByText('1–50 of 51',{exact:true}).waitFor();
  const query=new URL(page.url()).searchParams;
  assert.equal(query.get('offset'),'0');assert.equal(query.get('os_family'),'windows');
  assert.equal(query.get('os_search'),'Server 2022');assert.deepEqual(query.getAll('tag'),['tier:critical','location']);
  assert((await page.locator('#filter-chips').textContent()).includes('Asset tag: tier:critical'));
  await page.reload();await page.getByText('51 assets matching this scope and filters.').waitFor();
  assert.equal(await page.locator('#os-search').inputValue(),'Server 2022');
  await page.screenshot({path:'/tmp/vcm-assets-desktop.png',fullPage:false});
  await page.locator('#os-family').selectOption('unknown');
  await page.getByRole('button',{name:'Apply filters',exact:true}).click();
  await page.getByText('No assets match these filters.').waitFor();
  assert(await page.locator('#next').isDisabled());
  await page.getByRole('button',{name:'Clear filters',exact:true}).click();
  await page.getByText('51 assets matching this scope and filters.').waitFor();
  assert.equal(await page.locator('#os-search').inputValue(),'');
  fail=true;await page.getByRole('button',{name:'Apply filters',exact:true}).click();
  await page.locator('#page-error').waitFor();assert.equal(await page.locator('#asset-rows a').count(),0);
  fail=false;await page.getByRole('button',{name:'Apply filters',exact:true}).click();
  await page.getByText('51 assets matching this scope and filters.').waitFor();
  let release;
  const delayed=new Promise(resolve=>{release=resolve;});
  await page.route('**/api/assets?**', async route=>{
   if(new URL(route.request().url()).searchParams.get('tenant_id')!=='a')return route.fallback();
   await delayed;return route.fulfill({contentType:'application/json',body:JSON.stringify({items:[{...asset,fqdn:'Late client A'}],total:1,offset:0,limit:50})});
  });
  const pending=page.waitForRequest(req=>req.url().includes('/api/assets?') && req.url().includes('tenant_id=a'));
  await page.getByRole('button',{name:'Apply filters',exact:true}).click();await pending;
  await page.locator('#tenant').selectOption('b');
  await page.getByText('51 assets matching this scope and filters.').waitFor();release();
  await page.waitForLoadState('networkidle');
  assert(!(await page.locator('#asset-rows').textContent()).includes('Late client A'));
  assert((await page.locator('#scope-summary').textContent()).startsWith('Client B'));
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('.table-scroll').focus();
  await page.keyboard.press('ArrowRight');
  assert(await page.locator('.table-scroll').evaluate(el=>el===document.activeElement));
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'/tmp/vcm-assets-mobile.png',fullPage:false});
  await page.route('**/api/assets/asset-a?**',route=>route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({detail:'Asset not found for this client'})}));
  await page.goto(base+'/asset.html?tenant_id=b&asset_id=asset-a');
  await page.getByText('Asset not found for this client',{exact:true}).waitFor();
  assert.equal(await page.locator('#asset-detail').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: inventory pagination/filter URLs, safe text, detail snapshots, return focus/state, empty/error/retry, late client requests, mobile table keyboard access');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
