const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const base = process.env.VCM_PORTAL_URL || 'http://127.0.0.1:8080';
(async () => {
  const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
  try {
    const page = await browser.newPage();
    const external = [];
    page.on('request', req => { if (!req.url().startsWith(base)) external.push(req.url()); });
    await page.route('**/api/**', route => {
      const url = new URL(route.request().url());
      let body;
      if (url.pathname === '/api/tenants') body = [{id:'a',name:'Client A',slug:'a',status:'active'},{id:'b',name:'Client B',slug:'b',status:'active'}];
      else if (url.pathname.includes('/tenants/')) body = [{id:'env-'+url.pathname.split('/')[3],name:'Production',kind:'production',match_key:'ip'}];
      else if (url.pathname.endsWith('/imports')) body = [];
      else body = {posture_score:80,totals:{active:1,vulnerabilities:1,compliance:0,false_positive:0,risk_accepted:0},ad_health:[],severity_distribution:{critical:0,high:1,medium:0,low:0,info:0},stig_distribution:{CAT_I:0,CAT_II:0,CAT_III:0,untagged:0},trend:[],top_rules:[{rule_id:'19506',title:'Nessus scan information',severity:'info',affected_assets:2},{rule_id:'10042',title:'Unsupported operating system',severity:'high',affected_assets:1}],top_hosts:[{fqdn:'srv-prod-01.example.test',open_findings:12,open_crit_high:4},{ip:'192.0.2.42',open_findings:3,open_crit_high:1}]};
      return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
    });
    await page.goto(`${base}/?tenant_id=a&environment_id=env-b`);
    await page.locator('#k-active', {hasText:'1'}).waitFor();
    assert.equal(await page.locator('#environment').inputValue(),'','Reject another client’s environment');
    const scopedRequest = page.waitForRequest(req => req.url().includes('/api/dashboard?') && req.url().includes('environment_id=env-a'));
    await page.getByLabel('Environment', {exact:true}).selectOption('env-a');
    await scopedRequest;
    await page.locator('#k-active', {hasText:'1'}).waitFor();
    assert((await page.locator('#rep-exec').getAttribute('href')).includes('environment_id=env-a'));
    await page.getByRole('link',{name:'Clients & environments',exact:true}).click();
    await page.locator('#environment-list td', {hasText:'Production'}).first().waitFor();
    assert.equal(new URL(page.url()).searchParams.get('environment_id'),'env-a');
    assert((await page.locator('#scope-summary').textContent()).includes('Client A / Production'));
    await page.getByRole('link',{name:'Overview',exact:true}).click();
    await page.locator('#k-active', {hasText:'1'}).waitFor();
    assert.equal(await page.locator('#environment').inputValue(),'env-a');
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.equal(await page.locator('#app-sidebar').isVisible(),false);
    await page.getByRole('button',{name:'Menu',exact:true}).click();
    assert(await page.locator('#app-sidebar').isVisible());
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#app-sidebar').isVisible(),false);
    assert.equal(await page.locator('#menu-toggle').evaluate(el => el === document.activeElement),true);
    await page.getByLabel('Client', {exact:true}).selectOption('b');
    await page.locator('#k-active', {hasText:'1'}).waitFor();
    assert.equal(await page.locator('#environment').inputValue(),'');
    assert(!new URL(page.url()).searchParams.has('environment_id'));
    assert.deepEqual(external,[],'Runtime assets must be local');
    await page.screenshot({path:'/tmp/vcm-shell-mobile.png',fullPage:true});
    let release;
    const delayed = new Promise(resolve => {release = resolve;});
    await page.route('**/api/tenants/a/environments', async route => {
      await delayed;
      await route.fulfill({contentType:'application/json',body:JSON.stringify([{id:'env-a',name:'Late A'}])});
    });
    const pending = page.waitForRequest('**/api/tenants/a/environments');
    await page.locator('#tenant').selectOption('a'); await pending;
    await page.locator('#tenant').selectOption('b');
    await page.locator('#k-active', {hasText:'1'}).waitFor(); release();
    await page.waitForLoadState('networkidle');
    assert(!(await page.locator('#environment').textContent()).includes('Late A'));
    assert((await page.locator('#scope-summary').textContent()).startsWith('Client B'));
    await page.unroute('**/api/tenants/a/environments');
    await page.setViewportSize({width:1440,height:1000});
    await page.screenshot({path:'/tmp/vcm-shell-desktop.png',fullPage:true});
    await page.route('**/api/tenants/a/environments', route => route.fulfill({status:503,body:'unavailable'}));
    await page.locator('#tenant').selectOption('a');
    await page.locator('#dashboard-error').waitFor();
    assert.equal(await page.locator('#rep-exec').getAttribute('aria-disabled'),'true');
    assert(await page.locator('#environment').isDisabled());
    console.log('PASS: shared navigation, validated scope, environment dashboard/reports, mobile keyboard menu, local assets');
  } finally {await browser.close();}
})().catch(error => {console.error(error);process.exitCode=1;});
